### ISSUE TITLE
chrome space bar problem

### ISSUE THREAD

**Issue by KiPSOFT-zz** [chjj/term.js#48]
hi;

i'm using chrome 37.0.2062.124 and i have a space key problem. library not catch space key and not triggered data event. i'm testing on firefox 32 nothing problem.

thanks.

**Comment by IonicaBizau** [comment]
@KiPSOFT Oh, man, thanks! :cake:

**Comment by IonicaBizau** [comment]
@KiPSOFT I created a PR with that change: https://github.com/chjj/term.js/pull/89

**Comment by KiPSOFT** [comment]
Great. Thanks.
